### ISSUE TITLE
/hero/uhid/email endpoint does not function

### ISSUE THREAD

**Issue by ccrueb** [TheTabletop/CityGate#25]
Description:
Attempting to use this endpoint does not work
Severity:
Medium
Comments:
The problem seems to be on line 264 of hero.py where `if hname is None:` should be `if email is None:`

**Comment by QMalcolm** [comment]
Thats what I get for the excessively quick refactoring of the hero.py

**Comment by QMalcolm** [comment]
If statement has been updated. Route now properly updates email on_post, and returns email on_get
